# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-11 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_auto_20210210_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_image',
            new_name='image',
        ),
    ]
