# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-11 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_auto_20210211_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BORROWER',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
